### ISSUE TITLE
Files listed as Gerbers are Eagle's Proprietary Files

### ISSUE THREAD

**Issue by Upcycle-Electronics** [akshaybaweja/Smart-IC-Tester#2]
I cloned and tried to view your files but the zip files are only visible in Eagle, they are not Gerbers as labeled. This project really needs some basic pictures or PDF's of the schematic, wiring and/or PCB layout, if not the actual Gerbers. Lots of people have forked this but none of them have branched beyond the last commit here. It's a nice project but still not the easiest to replicate without reverse engineering the circuit from software. No one uses Eagle any more unless they enjoy burning money.

**Comment by jaylingelbach** [comment]
If you have Eagle installed it's fairly simple to convert the files to gerber. Plenty of info on YouTube to guide you :)
