### ISSUE TITLE
4020

### ISSUE THREAD

**Issue by kalymos** [akshaybaweja/Smart-IC-Tester#7]
Hello
I noticed an error in the test file, the 4020 test does not work.
I corrected the error. The functional test is here.

$4020
16 
LLLLLLLGL01LLLLV
LLLLLLLGL00LLLLV
LLLLLLLGHC0LLLLV
LLLLLLLGLC0LLLLV
LLLLLLLGHC0LLLLV
LLLLLLLGLC0LLLLV
LLLLLLLGHC0LLLLV
LLLLLLLGLC0LLLLV
LLLLLLLGHC0LLLLV
LLLLLLHGLC0LLLLV
LLLLLLHGHC0LLLLV
LLLLLLHGLC0LLLLV
LLLLLLHGHC0LLLLV
LLLLLLHGLC0LLLLV
LLLLLLHGHC0LLLLV
LLLLLLHGLC0LLLLV
LLLLLLHGHC0LLLLV
LLLLHLLGLC0LLLLV

**Comment by zedthirteen** [comment]
Thanks,

 

I’ll check that out = and thanks for sharing your project J

 

Regards

David

**Comment by akshaybaweja** [comment]
Updated [4020 IC](https://github.com/akshaybaweja/Smart-IC-Tester/commit/740d8dd92dd6f6c609b55e576abbf5ee73121b50)
