### ISSUE TITLE
Please add a schematic

### ISSUE THREAD

**Issue by bissonex** [akshaybaweja/Smart-IC-Tester#8]
Hi could you please add a schematic and a bill of material (BOM) to the project please?

**Comment by zedthirteen** [comment]
While it could be added here the schematic is available on the instructables web article https://www.instructables.com/Smart-IC-Tester/

I think Eagle files are also available in the file IC-Tester.zip on that article

Hope that helps for now

**Comment by akshaybaweja** [comment]
Hey @bissonex,
As said by @zedthirteen the instructions are available on [instructables](https://www.instructables.com/Smart-IC-Tester/). Kindly refer to that.
Thanks :)
