### ISSUE TITLE
4053 Test

### ISSUE THREAD

**Issue by rafaelcamacho** [akshaybaweja/Smart-IC-Tester#9]
Hi,

If you search for 16 pins IC, without a IC in ZIF, will return CI 4053.

Maybe the test pattern are wrong.

**Comment by akshaybaweja** [comment]
Hey,
I tried it on my tester and it worked fine. Try testing for shorts in your IC tester, some pins might be passing the test for IC 4053, or could be set in that pattern.
I'll close the issue, kindly reopen it if it didn't workout for you.

Happy Making :)
